build.gradle
src/main/java/com/avab/avab/config/SwaggerConfig.java
src/main/java/com/avab/avab/controller/RootController.java
src/main/resources/application.yml

Close #6 
- Swagger UI 라이브러리 추가 및 설정
- Swagger 라이브러리 추가
- `SwaggerConfig` 클래스 추가
- `application.yml` swagger 관련 설정 추가

:sparkles: [Feat]: Swagger UI 라이브러리 추가 및 설정

---

src/main/java/com/avab/avab/config/EnableJpaAuditingConfig.java
src/main/java/com/avab/avab/domain/Recreation.java
src/main/java/com/avab/avab/domain/RecreationAge.java
src/main/java/com/avab/avab/domain/RecreationGender.java
src/main/java/com/avab/avab/domain/RecreationHashtag.java
src/main/java/com/avab/avab/domain/RecreationKeyword.java
src/main/java/com/avab/avab/domain/RecreationPlace.java
src/main/java/com/avab/avab/domain/RecreationPreparation.java
src/main/java/com/avab/avab/domain/RecreationReview.java
src/main/java/com/avab/avab/domain/RecreationWay.java
src/main/java/com/avab/avab/domain/User.java
src/main/java/com/avab/avab/domain/common/BaseEntity.java
src/main/java/com/avab/avab/domain/enums/Age.java
src/main/java/com/avab/avab/domain/enums/Gender.java
src/main/java/com/avab/avab/domain/enums/Keyword.java
src/main/java/com/avab/avab/domain/enums/Place.java
src/main/java/com/avab/avab/domain/enums/RecommendationType.java
src/main/java/com/avab/avab/domain/enums/SocialType.java
src/main/java/com/avab/avab/domain/mapping/RecreationFavorite.java
src/main/java/com/avab/avab/domain/mapping/RecreationRecreationKeyword.java
src/main/java/com/avab/avab/domain/mapping/RecreationReviewRecommendation.java

Close #11 
- 엔티티 생성
- ERD 일부 수정
- ERD에 맞게 엔티티 생성했습니다.
- AQuery에서 생성된 SQL 문으로 먼저 테이블 생성하고, 서버 실행했을 때 DB에 수정되는 것 없도록 정제했습니다.
- 정제하면서 ERD 일부분 수정되었습니다. (타입,이름)
바뀐 거 비교하는 스샷 찍어둘 걸 그랬네요... 일단 ERD 보시면서 바뀐 부분 확인해보시면 될 것 같습니다.
- 연관관계 편의 메소드는 일단 해놓을까 하다가 안 했습니다 
(필요 없는 연관 관계도 있으니깐)
(나중에 필요하게 되면 추가합시다)
- DynamicInsert, DynamicUpdate는 일단 뺐습니다. (나중에 에러 생기면 그 때 추가합시다!)

✨ [Feat]: Entity 생성

---

build.gradle
src/main/java/com/avab/avab/apiPayload/code/status/ErrorStatus.java
src/main/java/com/avab/avab/apiPayload/exception/auth/AuthException.java
src/main/java/com/avab/avab/auth/filter/JwtRequestFilter.java
src/main/java/com/avab/avab/auth/jwt/JwtTokenProvider.java
src/main/java/com/avab/avab/auth/principal/PrincipalDetails.java
src/main/java/com/avab/avab/auth/principal/PrincipalDetailsService.java
src/main/java/com/avab/avab/auth/test/AuthController.java
src/main/java/com/avab/avab/auth/test/AuthService.java
src/main/java/com/avab/avab/auth/test/dto/LoginRequest.java
src/main/java/com/avab/avab/auth/test/dto/LoginResponse.java
src/main/java/com/avab/avab/config/SecurityConfig.java
src/main/java/com/avab/avab/domain/Recreation.java
src/main/java/com/avab/avab/domain/RecreationAge.java
src/main/java/com/avab/avab/domain/RecreationGender.java
src/main/java/com/avab/avab/domain/RecreationHashtag.java
src/main/java/com/avab/avab/domain/RecreationKeyword.java
src/main/java/com/avab/avab/domain/RecreationReview.java
src/main/java/com/avab/avab/domain/mapping/RecreationFavorite.java
src/main/java/com/avab/avab/repository/UserRepository.java
src/main/resources/application.yml

- security config 설정
- jwt 설정
Close #13 
- 시큐리티 설정
- security config 추가
- jwt 기능 추가
- 현재는 cors를 Default로 놔두었는데 나중에 고쳐야할지
- jwt를 받을려면 관련 controller가 필요할 것 같아서 일단 놔두었습니다.
- 카카오 callback 주소는 아직 전체 권한 부여를 해놓지 않았습니다.
- 아직 redis는 설정하지 않았습니다.
- 현재는 ROLE_USER에 대해서만 해놓았는데 다른 role도 필요한 지

Feat: 시큐리티 설정

---

src/main/java/com/avab/avab/config/SecurityConfig.java

- healthcheck 권한 없이 접근 가능 수정
Close #16 
- 시큐리티 배포 실패(수정)
- healthcheck 권한 없이 접근 가능

:bug: Fix: 시큐리티 수정

---

build.gradle
src/main/java/com/avab/avab/AvAbApplication.java
src/main/resources/application.yml

Close #19 
- Redis 연결 설정
- `@EnableRedisRepositories` 추가
- `application.yml` redis 연결 관련 추가
- redis 의존성 추가
- SpringBoot에서는 Redis 접근을 Repository와 RedisTemplate을 이용한다고 합니다.
1. Repository의 경우 우리가 JPA에서 사용하는 Repository와 동일한 방식을 쓰되,
CrudRepository를 extends 하면 된다고 합니다!
3. RestTemplate은 좀 더 세세한 방식으로 자체 메소드를 사용해서 접근하는 듯합니다.
위의 방식들을 종합적으로 고려하였을 때, 1번 방식이 저희에게 가장 친숙하고 기타 설정이 필요 없어서 1번으로 가려 합니다.
다른 의견 환영합니다!!
- redis 관련 파일들은 이제 redis 패키지 밑에 두려고 합니다.
- redis
- domain
- `RefreshToken.java`
- `RecreationHit.java`
- service
- `RedisService.java`
- impl
- `RedisServiceImpl.java`
- repository
- `RefreshTokenRepository`
이런 너낌으로 디렉터리 구조로 가져가려 합니다!
- 기타 Redis와 관련된 것들은 저도 미숙한 상태니 스스로 찾아봐주세요...(쭈굴)

:sparkles: [Feat]: Redis 연결 설정

---

src/main/java/com/avab/avab/apiPayload/BaseResponse.java
src/main/java/com/avab/avab/apiPayload/exception/ExceptionAdvice.java
src/main/java/com/avab/avab/auth/test/AuthController.java
src/main/java/com/avab/avab/config/SecurityConfig.java
src/main/java/com/avab/avab/controller/RecreationController.java
src/main/java/com/avab/avab/converter/RecreationConverter.java
src/main/java/com/avab/avab/domain/Recreation.java
src/main/java/com/avab/avab/dto/recreation/RecreationResponseDTO.java
src/main/java/com/avab/avab/repository/RecreationRepository.java
src/main/java/com/avab/avab/service/RecreationService.java
src/main/java/com/avab/avab/service/impl/RecreationServiceImpl.java

조회수를 기준으로 레크레이션 목록을 조회하는 API
Close #18 
- 인기 레크레이션 목록을 조회하는 API
RecreationController, RecreationService(Impl), RecreationRepository, RecreationResponseDTO, RecreationConverter 추가
SecurityConfig에 인기목록조회 엔드포인트 추가

✨  [FEAT]: 인기 레크레이션 목록 조회 API

---

.script/pre-commit
build.gradle
src/main/java/com/avab/avab/controller/RecreationController.java

Close #33 
- pre-commit git hook 추가
- pre-commit git hook
86aec253a653d75c56b962640d98258d51cadc48
현재 코드 컨벤션 적용을 위해서는 커밋 전에 서버를 한 번 실행하는 것이 필수입니다.
하지만 이름 변경, 오타 수정과 같은 서버 실행이 불필요한 수정 같은 경우 서버 실행을 까먹어서 코드 컨벤션이 적용되지 않는 일들이 반복적으로 발생하고 있습니다.
이를 해결하기 위해 커밋하면 자동으로 코드 포맷팅을 진행한 뒤 변경된 사항을 다시 추가하여 커밋하는 git hook을 추가하였습니다.
여러분들께서 적용하기 편하시라고 제가 세팅하는 코드를 미리 `build.gradle`에 추가해두었습니다.
적용은 그냥 서버 한 번 실행하면 그 이후부터는 알아서 git hook이 동작해서 포맷팅이 될겁니다!!

:construction_worker: [CI]: 코드 포맷팅을 위한 pre-commit Git Hooks 추가

---

src/main/java/com/avab/avab/batch/UpdateRecreationViewCountConfig.java
src/main/java/com/avab/avab/repository/RecreationRepository.java

Close #51 
- 조회수 업데이트 배치 추가 구현

:sparkles: [Feat]: 주간 조회수 업데이트 배치 추가

---

src/main/java/com/avab/avab/controller/UserController.java
src/main/java/com/avab/avab/converter/UserConverter.java
src/main/java/com/avab/avab/domain/User.java
src/main/java/com/avab/avab/dto/reqeust/UserRequestDTO.java
src/main/java/com/avab/avab/dto/response/UserResponseDTO.java
src/main/java/com/avab/avab/service/UserService.java
src/main/java/com/avab/avab/service/impl/UserServiceImpl.java

Close #46 
- 회원의 닉네임을 수정하는 API 입니다.

:sparkles: [Feat]: 회원 정보 수정 API 구현

---

src/main/java/com/avab/avab/controller/RecreationController.java
src/main/java/com/avab/avab/controller/UserController.java
src/main/java/com/avab/avab/converter/RecreationConverter.java
src/main/java/com/avab/avab/domain/enums/Keyword.java
src/main/java/com/avab/avab/repository/RecreationCustomRepository.java
src/main/java/com/avab/avab/repository/RecreationCustomRepositoryImpl.java
src/main/java/com/avab/avab/service/RecreationService.java
src/main/java/com/avab/avab/service/impl/RecreationServiceImpl.java

Close #54 
- 레크레이션 검색 수정
- 키워드 추가
- API 문서 수정
c6f11afdb72d27e57bc4ab0635d78c089220d074
해시태그와 목적이 분리됨에 따라 목적 조건이 하나 더 늘었습니다.
목적 조건을 검색 조건에 추가했습니당.
9b45db120868880820278dcc404e8893b97ff664
노션 정책집에 있는 키워드 대로 추가했습니다.
773153870d396b9719169743958eb7bbc3257d92
이모티콘 추가했습니다

✨ [Feat]: 레크레이션 검색 요구사항에 맞추어 수정 

---

src/main/generated/com/avab/avab/domain/QFlow.java
src/main/generated/com/avab/avab/domain/QUser.java
src/main/generated/com/avab/avab/domain/mapping/QFlowFavorite.java
src/main/java/com/avab/avab/domain/Flow.java
src/main/java/com/avab/avab/domain/User.java
src/main/java/com/avab/avab/domain/mapping/FlowFavorite.java

- FlowFavorite 매핑 테이블 추가
Close #56 
- 플로우 즐겨찾기 추가 및 조회수 추가
- 플로우 mapping 테이블 추가

:sparkles: [Feat]: 플로우 즐겨 찾기 추가

---

src/main/generated/com/avab/avab/domain/QFlow.java
src/main/generated/com/avab/avab/domain/QFlowAge.java
src/main/generated/com/avab/avab/domain/QFlowGender.java
src/main/generated/com/avab/avab/domain/QUser.java
src/main/generated/com/avab/avab/domain/mapping/QFlowFavorite.java
src/main/generated/com/avab/avab/domain/mapping/QFlowRecreation.java
src/main/generated/com/avab/avab/domain/mapping/QFlowRecreationKeyword.java
src/main/generated/com/avab/avab/domain/mapping/QFlowRecreationPurpose.java
src/main/java/com/avab/avab/controller/FlowController.java
src/main/java/com/avab/avab/converter/FlowConverter.java
src/main/java/com/avab/avab/domain/Flow.java
src/main/java/com/avab/avab/domain/User.java
src/main/java/com/avab/avab/domain/mapping/FlowFavorite.java
src/main/java/com/avab/avab/dto/response/FlowResponseDTO.java
src/main/java/com/avab/avab/repository/FlowRepository.java
src/main/java/com/avab/avab/security/SecurityConfig.java
src/main/java/com/avab/avab/service/FlowService.java
src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java

Close #61 
- 플로우 엔티티 수정
- 플로우 조회 API 구현
56245a378e6367dddf09876d7421f483e8f284e0
작성자랑 스크랩 개수가 없어서 추가했습니당
61850817deb58b6d4f8fa6e8e99340e04962bb67
최신순으로 조회되게 했습니다.

✨ [Feat]: 플로우 목록 조회 API 구현

---

src/main/java/com/avab/avab/controller/AuthController.java
src/main/java/com/avab/avab/controller/UserController.java
src/main/java/com/avab/avab/repository/FlowRepository.java
src/main/java/com/avab/avab/security/test/TestAuthController.java
src/main/java/com/avab/avab/service/UserService.java
src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java
src/main/java/com/avab/avab/service/impl/UserServiceImpl.java

Close #63 
- 내가 만든 플로우 조회 API
- API 문서 일부 수정
809a928fda0750f97bb7f400b29ccdfb8b6956d3
c983b621da899c6494e5ead083f00184fa6f2338
인증/인가 관련 태그 추가했습니다.

✨ [Feat]: 내가 만든 플로우 조회 API

---

src/main/java/com/avab/avab/converter/RecreationConverter.java
src/main/java/com/avab/avab/dto/response/RecreationResponseDTO.java

Close #69 
- 레크레이션 프리뷰 DTO에 summary 추가
디자인에 hover시 summary가 보여야 해서 수정했습니다.

:sparkles: [Feat]: 레크레이션 프리뷰 응답에 summary 추가

---

src/main/generated/com/avab/avab/domain/mapping/QFlowRecreation.java
src/main/java/com/avab/avab/controller/FlowController.java
src/main/java/com/avab/avab/converter/FlowConverter.java
src/main/java/com/avab/avab/domain/Flow.java
src/main/java/com/avab/avab/domain/mapping/FlowRecreation.java
src/main/java/com/avab/avab/dto/reqeust/FlowRequestDTO.java
src/main/java/com/avab/avab/repository/RecreationKeyWordRepository.java
src/main/java/com/avab/avab/repository/RecreationKeywordRepository.java
src/main/java/com/avab/avab/repository/RecreationPurposeRepository.java
src/main/java/com/avab/avab/service/FlowService.java
src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java

Close #66 
- 플로우를 생성하는 API 입니다.
- FlowRecreation 테이블에 Integer seq를 추가했습니다.

✨  [Feat]: 플로우 생성 API

---

src/main/java/com/avab/avab/config/RedisConfig.java

Close #81 
- 배포 서버에서 레디스 연결 문제 해결
5a9edccc96753d9cb82fb8c4a6605ffc8bf7f451

:ambulance: [HOTFIX]: 레디스 연결 문제 해결

---

src/main/java/com/avab/avab/controller/RecreationController.java
src/main/java/com/avab/avab/repository/RecreationCustomRepository.java
src/main/java/com/avab/avab/repository/RecreationCustomRepositoryImpl.java
src/main/java/com/avab/avab/repository/RecreationRepository.java
src/main/java/com/avab/avab/security/SecurityConfig.java
src/main/java/com/avab/avab/service/RecreationService.java
src/main/java/com/avab/avab/service/impl/RecreationServiceImpl.java

Close #85
-  최신 레크레이션 목록 API 구현했습니다. 
- 최신 레크레이션 목록 API 추가했습니다

:sparkles: [Feat] 최신 레크레이션 목록 API 구현

---

src/main/java/com/avab/avab/controller/AuthController.java
src/main/java/com/avab/avab/controller/FlowController.java
src/main/java/com/avab/avab/controller/RecreationReviewController.java
src/main/java/com/avab/avab/controller/UserController.java
src/main/java/com/avab/avab/security/SecurityConfig.java

Close #80 
- 엔드포인트 및 문서 수정
###엔드포인트 및 문서 수정
어색한 표현이랑 엔드포인트 수정했습니다!

:memo: [Docs]: 엔드포인트 및 문서 수정

---

src/main/java/com/avab/avab/converter/RecreationConverter.java
src/main/java/com/avab/avab/dto/reqeust/RecreationRequestDTO.java

Close #88 
- 레크레이션 생성 DTO 누락된 Gender 추가
- 일부 필드 null check
6f78013dbc9e0636d97d14d8c1da0cbf181ac440
몇몇 필드는 필수가 아니라서 NPE 방지를 위해 Null Check 추가 했습니다

:bug: [Fix]: Gender 추가 및 null check 추가

---

src/main/java/com/avab/avab/controller/FlowController.java
src/main/java/com/avab/avab/converter/FlowConverter.java
src/main/java/com/avab/avab/dto/response/FlowResponseDTO.java
src/main/java/com/avab/avab/repository/FlowFavoriteRepository.java
src/main/java/com/avab/avab/repository/FlowRepository.java
src/main/java/com/avab/avab/service/FlowService.java
src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java

Close #79 
- 플로우 스크랩 기능 구현
20c4b1797e8233901ded8262e029c09959ff4846
스크랩 되어 있으면 취소, 되어 있지 않으면 스크랩하는 API 입니다.

✨ [Feat]: 플로우 스크랩 API 구현

---

src/main/java/com/avab/avab/controller/RecreationController.java
src/main/java/com/avab/avab/converter/RecreationConverter.java
src/main/java/com/avab/avab/dto/response/RecreationResponseDTO.java
src/main/java/com/avab/avab/security/SecurityConfig.java

Close #89
- 레크레이션 상세페이지 추가 및 최신레크레이션 api 수정 
1. fabc34a378f5b8dffd4cd6f163f4b833716d4fbe
상세설명에 **1.제목 2.키워드 3.장소 4.진행시간** 추가했고 
way에 **seq**추가했습니다. 
2. 2461280572e9811e93cdcc4b0541f1dd9c05a375
최신레크레이션 api 이름 recent빼는 방향으로 수정했습니다.

✨ [Feat] 레크레이션 상세페이지 추가 및 최신레크레이션 api 수정 

---

src/main/java/com/avab/avab/controller/AuthController.java
src/main/java/com/avab/avab/controller/RecreationController.java

Close #97 
c258d5ba2d947bddba579dd68e03aabb3151da85
- user 숨기기
1ba3eefbb827d4386e32dd3d803b02c900bd67c1
- 닉네임 변환

📝 [Docs]: 로그인 swagger 수정

---

src/main/java/com/avab/avab/controller/RecreationController.java
src/main/java/com/avab/avab/repository/RecreationCustomRepository.java
src/main/java/com/avab/avab/repository/RecreationCustomRepositoryImpl.java
src/main/java/com/avab/avab/service/impl/RecreationServiceImpl.java

Close #95 
- 리뷰 게시 시 평점 업데이트
7ec192171e8001ac12492c34bc21ac0fb688f447
트리거 기능을 쓸지... 애플리케이션에서 처리할지 고민하다가
일단 후자로 택했습니다.
트리거 써봤는데 좀 별로인 느낌이 있어서...

:bug: [Fix]: 레크레이션 리뷰 게시할 때 별점 업데이트 되도록 수정

---

src/main/java/com/avab/avab/controller/RecreationController.java
src/main/java/com/avab/avab/converter/RecreationConverter.java
src/main/java/com/avab/avab/dto/response/RecreationResponseDTO.java
src/main/java/com/avab/avab/security/SecurityConfig.java

Close #99
- 레크레이션 상세페이지 불러올 내역 추가했습니다
확인해보니 **스크랩여부, 별점, 목적** 도 추가가 안되어있어서 추가했습니다! 0987bd9a49e22688559193d6023188636ca10303
securityconfig 코드 컨벤션 적용했습니다  957941a1cfabe76cb2e052939706328cd01bf92c

✨ [Feat] 레크레이션 상세페이지 불러올 내역 추가

---

src/main/java/com/avab/avab/domain/enums/Age.java
src/main/java/com/avab/avab/domain/enums/Keyword.java
src/main/java/com/avab/avab/domain/enums/Purpose.java

Close #101 
- enum 수정
Purpose, Age 수정했습니다.
확인해보니 Keyword도 하나 누락되어 있어서 추가했습니다.

:recycle: [Refactor]: 요구사항에 맞추어 enum 수정

---

src/main/java/com/avab/avab/apiPayload/code/status/ErrorStatus.java
src/main/java/com/avab/avab/apiPayload/exception/FlowException.java
src/main/java/com/avab/avab/controller/FlowController.java
src/main/java/com/avab/avab/converter/FlowConverter.java
src/main/java/com/avab/avab/dto/response/FlowResponseDTO.java
src/main/java/com/avab/avab/service/FlowService.java
src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java

✨  [Feat]: 플로우 삭제 API 구현

---

src/main/java/com/avab/avab/controller/AuthController.java
src/main/java/com/avab/avab/converter/AuthConverter.java
src/main/java/com/avab/avab/service/impl/AuthServiceImpl.java
src/main/java/com/avab/avab/utils/RandomUsername.java

Close #103 
- 회원가입 시 닉네임 랜덤 생성
f5b8ac51a08b1b63fa729ec99847b99e87e9a2da

✨ [Feat]: 회원가입시 닉네임 랜덤 생성

---

src/main/generated/com/avab/avab/domain/QCustomRecreation.java
src/main/generated/com/avab/avab/domain/mapping/QFlowRecreation.java
src/main/generated/com/avab/avab/domain/mapping/QRecreationRecreationKeyword.java
src/main/java/com/avab/avab/domain/CustomRecreation.java
src/main/java/com/avab/avab/domain/mapping/FlowRecreation.java
src/main/java/com/avab/avab/domain/mapping/RecreationRecreationKeyword.java

Close #105 
- 엔티티 수정
0d0a3d4d5f8eff56fddf63591f06e90f5e7ea337
설계 대로 엔티티 수정 및 추가했습니다.
`FlowRecreation`이랑 `CustomRecreation`은 1대1 관계로 설정했습니다.

✨ [Feat]: 플로우 관련 엔티티 수정

---

src/main/java/com/avab/avab/security/SecurityConfig.java

Close #108 
- `SecurityConfig` 수정
url 오타 수정했습니다!

:bug: [Fix]: 플로우 목록 조회 인증 요구하는 문제 해결

---

src/main/java/com/avab/avab/security/SecurityConfig.java
src/main/java/com/avab/avab/security/filter/AuthExceptionHandlingFilter.java

Close #110 
- JWT 필터에서 발생한 예외 핸들링하는 필터 추가
`JwtRequestFilter` 도중 예외가 발생하면 핸들링이 안돼서 500이 터집니다
필터 내부에서 발생한 예외를 처리하는 필터 추가했습니다!

:sparkles: [Feat]: AuthException 처리하는 예외 핸들링 필터 추가

---

src/main/java/com/avab/avab/controller/FlowController.java
src/main/java/com/avab/avab/controller/RecreationController.java
src/main/java/com/avab/avab/repository/FlowCustomRepository.java
src/main/java/com/avab/avab/repository/FlowCustomRepositoryImpl.java
src/main/java/com/avab/avab/repository/FlowRepository.java
src/main/java/com/avab/avab/security/SecurityConfig.java
src/main/java/com/avab/avab/service/FlowService.java
src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java

Close #112
- 플로우 생성시 추천플로우 api 구현
1. 플로우 생성시 추천플로우 api 구현 했습니다 25024299b73b18bfdebae3161f952e2b538e77fc
=> 제이미님이 구현하신 추천 레크레이션 로직 참고했습니다

✨ [Feat] 플로우 생성시 추천 플로우 API 구현

---

src/main/java/com/avab/avab/controller/FlowController.java
src/main/java/com/avab/avab/converter/FlowConverter.java
src/main/java/com/avab/avab/dto/reqeust/FlowRequestDTO.java
src/main/java/com/avab/avab/repository/CustomRecreationRepository.java
src/main/java/com/avab/avab/service/FlowService.java
src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java

Close #107 
- 플로우를 생성할때 기존 레크레이션과 사용자 지정 레크레이션을 모두 받을 수 있게 하였습니다.

♻️  [Refactor]: 플로우 생성에 사용자 지정 레크레이션 추가

---

src/main/java/com/avab/avab/converter/RecreationConverter.java
src/main/java/com/avab/avab/dto/response/RecreationResponseDTO.java

:sparkles: [Feat]: 레크레이션 리뷰 전체 개수 추가

---

src/main/java/com/avab/avab/controller/FlowController.java
src/main/java/com/avab/avab/converter/FlowConverter.java
src/main/java/com/avab/avab/dto/reqeust/FlowRequestDTO.java
src/main/java/com/avab/avab/dto/response/FlowResponseDTO.java
src/main/java/com/avab/avab/repository/FlowRepository.java
src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java

:ambulance: [HOTFIX!]: 플로우 스크랩, 플로우 생성 수정

---

src/main/java/com/avab/avab/converter/RecreationConverter.java
src/main/java/com/avab/avab/dto/response/RecreationResponseDTO.java

Close #120
- 레크레이션 상세페이지에 대표 이미지 추가했습니다

:sparkles: [Feat] 레크레이션 대표 이미지 추가

---

src/main/java/com/avab/avab/controller/FlowController.java
src/main/java/com/avab/avab/controller/RecreationController.java
src/main/java/com/avab/avab/converter/FlowConverter.java
src/main/java/com/avab/avab/converter/RecreationConverter.java
src/main/java/com/avab/avab/dto/response/FlowResponseDTO.java
src/main/java/com/avab/avab/dto/response/RecreationResponseDTO.java

Close #115 
- 플로우 요구사항 변경으로 상세 조회시 커스텀 레크레이션도 같이 조회될 수 있게 변경했습니다.
-

♻️  [Refactor]: 플로우 상세조회시 커스텀 레크레이션도 조회될 수 있게 변경

---

src/main/java/com/avab/avab/domain/Flow.java

Close #124 
- 스크랩 개수가 기본값으로 안들어가서 수정합니다.

:bug: [Fix]: DynamicUpdate, DynamicInsert 추가

---

src/main/java/com/avab/avab/controller/UserController.java
src/main/java/com/avab/avab/converter/UserConverter.java
src/main/java/com/avab/avab/dto/response/UserResponseDTO.java

Close #126 
- 인증된 사용자 정보 조회 API

:sparkles: [Feat]: 내 정보 조회 API 구현

---

src/main/java/com/avab/avab/controller/FlowController.java
src/main/java/com/avab/avab/converter/FlowConverter.java
src/main/java/com/avab/avab/domain/mapping/FlowRecreation.java
src/main/java/com/avab/avab/repository/CustomRecreationRepository.java
src/main/java/com/avab/avab/repository/FlowAgeRepository.java
src/main/java/com/avab/avab/repository/FlowGenderRepository.java
src/main/java/com/avab/avab/repository/FlowRecreationKeywordRepository.java
src/main/java/com/avab/avab/repository/FlowRecreationPurposeRepository.java
src/main/java/com/avab/avab/repository/FlowRecreationRepository.java
src/main/java/com/avab/avab/security/SecurityConfig.java
src/main/java/com/avab/avab/service/FlowService.java
src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java

- flow 수정 (모두 삭제한 후 작성)
Close #77 
- flow 수정 기능 구현
ad36c69216ef39addc9aea8d6c5aa468c307c133
- flow 수정

:sparkles: [Feat]: flow 수정 구현(일단 모두 삭제한 후 작성으로 구현)

---

build.gradle
src/main/java/com/avab/avab/AvAbApplication.java
src/main/java/com/avab/avab/apiPayload/code/status/ErrorStatus.java
src/main/java/com/avab/avab/apiPayload/exception/ExceptionAdvice.java
src/main/java/com/avab/avab/controller/FlowController.java
src/main/java/com/avab/avab/controller/UserController.java
src/main/java/com/avab/avab/converter/FlowConverter.java
src/main/java/com/avab/avab/domain/User.java
src/main/java/com/avab/avab/dto/reqeust/UserRequestDTO.java
src/main/java/com/avab/avab/feign/discord/DiscordFeignConfiguration.java
src/main/java/com/avab/avab/feign/discord/dto/DiscordMessage.java
src/main/java/com/avab/avab/feign/discord/service/DiscordClient.java
src/main/java/com/avab/avab/repository/CustomRecreationRepository.java
src/main/java/com/avab/avab/repository/FlowAgeRepository.java
src/main/java/com/avab/avab/repository/FlowGenderRepository.java
src/main/java/com/avab/avab/repository/FlowRecreationKeywordRepository.java
src/main/java/com/avab/avab/repository/FlowRecreationPurposeRepository.java
src/main/java/com/avab/avab/repository/FlowRecreationRepository.java
src/main/java/com/avab/avab/service/UserService.java
src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java
src/main/java/com/avab/avab/service/impl/UserServiceImpl.java

Close #129 
- 알 수 없는 예외 발생 시 디스코드 알림 기능 추가
- 닉네임 변경되지 않는 버그 수정
배포 환경에서 에러 발생 시 디스코드 알림 가도록 기능 구현했습니다.
Transactional 어노테이션 없어서 닉네임 수정 안되는 문제 해결했습니다.
추가적으로 닉네임 변경에서 좀 더 포괄적인 내 정보 수정로 변경했습니다.

✨ [Feat]: 디스코드 알림 기능 추가 + 기타

---

src/main/generated/com/avab/avab/domain/QFlow.java
src/main/java/com/avab/avab/converter/FlowConverter.java
src/main/java/com/avab/avab/domain/Flow.java
src/main/java/com/avab/avab/dto/response/FlowResponseDTO.java
src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java

- 플로우 생성 & 수정 시 랜덤 이미지 저장
- 플로우 상세, 목록 조회 시 이미지 리턴
Close #131 
- 플로우 랜덤 이미지관련 수정
- 플로우 랜덤 이미지관련 수정

:sparkles: [Feat]: 플로우 랜덤 이미지 추가

---

src/main/java/com/avab/avab/converter/FlowConverter.java
src/main/java/com/avab/avab/dto/response/FlowResponseDTO.java

:recycle: [Refactor]: 이미지 url flow 안으로 변경

---

src/main/java/com/avab/avab/controller/RecreationController.java
src/main/java/com/avab/avab/converter/RecreationConverter.java
src/main/java/com/avab/avab/dto/response/RecreationResponseDTO.java

- 레크레이션 추천 기능 플레이타임 추가
Close #134 
- 레크레이션 추천 기능 플레이타임 추가
-레크레이션 추천 기능 플레이타임 추가

✨ [Feat]: 레크레이션 추천 기능 플레이타임 추가

---

src/main/java/com/avab/avab/controller/RecreationController.java
src/main/java/com/avab/avab/converter/RecreationConverter.java
src/main/java/com/avab/avab/repository/RecreationCustomRepositoryImpl.java
src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java

🚑 [HOTFIX!]: 검색 인원 조건 수정

---

src/main/generated/com/avab/avab/domain/QUser.java
src/main/java/com/avab/avab/converter/UserConverter.java
src/main/java/com/avab/avab/domain/User.java
src/main/java/com/avab/avab/dto/response/UserResponseDTO.java

:ambulance: [HOTFIX!]: 사용자 프로필 이미지 추가

---

src/main/java/com/avab/avab/redis/domain/RefreshToken.java
src/main/java/com/avab/avab/redis/service/RefreshTokenService.java
src/main/java/com/avab/avab/security/provider/JwtTokenProvider.java

- refresh 만료 시 삭제 추가
Close #138 
- refresh 만료 시 삭제 추가
4801abe85a1eadc57e741173700015dd15eb6ee9
- refresh 만료 시 삭제 추가

:sparkles: [Feat]: refresh 만료 시 삭제 추가

---

src/main/java/com/avab/avab/batch/SchedulerConfig.java
src/main/java/com/avab/avab/controller/RecreationController.java
src/main/java/com/avab/avab/domain/Report.java
src/main/java/com/avab/avab/domain/enums/ReportType.java
src/main/java/com/avab/avab/redis/repository/RecreationViewCountRepository.java
src/main/java/com/avab/avab/redis/service/impl/RecreationViewCountServiceImpl.java
src/main/java/com/avab/avab/repository/RecreationCustomRepositoryImpl.java
src/main/java/com/avab/avab/service/RecreationService.java
src/main/java/com/avab/avab/service/impl/RecreationServiceImpl.java

Close #150
- 신고 엔티티 추가 했습니다  a9a40551b372c630ce787c45142cba92ea9756da
- 기존코드에 코드 컨벤션 적용되어있지 않아 적용했습니다. adad9d2654e5f769eaf87f99bc20b9ba7134ddb0

✨ [Feat] 신고 엔티티 생성

---

src/main/java/com/avab/avab/apiPayload/code/status/ErrorStatus.java
src/main/java/com/avab/avab/constant/UserConstant.java
src/main/java/com/avab/avab/controller/ReportController.java
src/main/java/com/avab/avab/converter/ReportConverter.java
src/main/java/com/avab/avab/domain/Flow.java
src/main/java/com/avab/avab/domain/Recreation.java
src/main/java/com/avab/avab/domain/RecreationReview.java
src/main/java/com/avab/avab/domain/Report.java
src/main/java/com/avab/avab/domain/User.java
src/main/java/com/avab/avab/domain/enums/ReportReason.java
src/main/java/com/avab/avab/domain/enums/ReportType.java
src/main/java/com/avab/avab/domain/enums/UserStatus.java
src/main/java/com/avab/avab/dto/reqeust/ReportRequestDTO.java
src/main/java/com/avab/avab/dto/response/ReportResponseDTO.java
src/main/java/com/avab/avab/repository/ReportRepository.java
src/main/java/com/avab/avab/security/SecurityConfig.java
src/main/java/com/avab/avab/security/filter/DisabledUserFilter.java
src/main/java/com/avab/avab/security/test/TestAuthController.java
src/main/java/com/avab/avab/service/AuthService.java
src/main/java/com/avab/avab/service/ReportService.java
src/main/java/com/avab/avab/service/UserService.java
src/main/java/com/avab/avab/service/impl/AuthServiceImpl.java
src/main/java/com/avab/avab/service/impl/ReportServiceImpl.java
src/main/java/com/avab/avab/service/impl/UserServiceImpl.java

Close #157 
- 레크레이션 리뷰 신고
다른 신고 기능과 동일

✨ [Feat]: 레크레이션 리뷰 신고 API

---

src/main/java/com/avab/avab/service/impl/RecreationServiceImpl.java

Close #163 
- 레크레이션 필터링 버그 해결
dc0f72af2d8861a2f18caedc30bfa7db8458edc6
- 레크레이션 정렬 수정 (SCRAP -> LIKE)

🐛 [Fix]: 레크레이션 필터링 버그 해결

---

src/main/java/com/avab/avab/controller/FlowController.java
src/main/java/com/avab/avab/controller/RecreationController.java
src/main/java/com/avab/avab/repository/FlowCustomRepository.java
src/main/java/com/avab/avab/repository/FlowCustomRepositoryImpl.java
src/main/java/com/avab/avab/repository/MaskingPredicates.java
src/main/java/com/avab/avab/repository/RecreationCustomRepository.java
src/main/java/com/avab/avab/repository/RecreationCustomRepositoryImpl.java
src/main/java/com/avab/avab/repository/RecreationRepository.java
src/main/java/com/avab/avab/repository/RecreationReviewRepository.java
src/main/java/com/avab/avab/service/FlowService.java
src/main/java/com/avab/avab/service/RecreationService.java
src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java
src/main/java/com/avab/avab/service/impl/RecreationServiceImpl.java

Close #164 
- 레크레이션 & 리뷰 마스킹
8e82e4e95ae2893e2fd2cd965fe232ffda10d9a0
- 연관 레크레이션 조회 마스킹
97c15c775457b03558ab407db3ed0ab1607f4140
d1cf9c0ada83b5a47731d29b9d6c580106c03ddb
- 레크레이션 상세 설명 마스킹
9dbefc4c4af414491247f4e4c469196ff353e28e
- 리뷰 조회 마스킹

🐛 [Fix] 레크레이션 & 리뷰 마스킹

---

src/main/java/com/avab/avab/controller/FlowController.java
src/main/java/com/avab/avab/domain/User.java
src/main/java/com/avab/avab/security/filter/DisabledUserFilter.java
src/main/java/com/avab/avab/service/impl/AuthServiceImpl.java

Close #167 
- 플로우 삭제 API URL 변경
- 활동정지된 사용자 URL 접근 불가 처리
/api/flows/delete/{flowId} -> /api/flows/{flowId}

🐛 [Fix]: 활동정지 사용자 필터 수정 구현

---

src/main/java/com/avab/avab/repository/MaskingPredicates.java

Close #171 
- user null일 경우 예외 처리 안함

:bug: [Fix]: 인기 레크레이션 미로그인시 조회 안되는 문제 수정

---

src/main/java/com/avab/avab/repository/RecreationCustomRepositoryImpl.java

Close #178 
- searchRecreations 코드 수정
e81aaa3e4231180c11feef18f5cd71bfba2e9ba3
- searchRecreations 코드 수정

🐛 [Fix]:  searchRecreations 코드 수정

---

src/main/java/com/avab/avab/domain/RecreationReview.java
src/main/java/com/avab/avab/security/SecurityConfig.java
src/main/java/com/avab/avab/security/test/dto/LoginRequest.java
src/main/java/com/avab/avab/service/impl/RecreationReviewServiceImpl.java

:bug: [Fix]: 리뷰 추천/비추천시 카운트 수정

---

build.gradle
src/main/java/com/avab/avab/security/SecurityConfig.java
src/main/resources/application.yml

Close #185 
- 프로메테우스 액츄에이터 추가
- 액추에이터 보안 설정
- 프로메테우스 액츄에이터 라이브러리 추가
- 액츄에이터 보안 설정
src/main/resources/application.yml
확인 하십쇼!

✨ [Feat]: 프로메테우스 액츄에이터 추가 및 설정

---

src/main/java/com/avab/avab/apiPayload/code/status/ErrorStatus.java
src/main/java/com/avab/avab/controller/RecreationController.java
src/main/java/com/avab/avab/converter/RecreationConverter.java
src/main/java/com/avab/avab/domain/Recreation.java
src/main/java/com/avab/avab/domain/Report.java
src/main/java/com/avab/avab/domain/User.java
src/main/java/com/avab/avab/dto/enums/MaskedReason.java
src/main/java/com/avab/avab/dto/response/RecreationResponseDTO.java
src/main/java/com/avab/avab/repository/FlowCustomRepositoryImpl.java
src/main/java/com/avab/avab/repository/FlowRepository.java
src/main/java/com/avab/avab/repository/MaskingPredicates.java
src/main/java/com/avab/avab/repository/QueryDslUtil.java
src/main/java/com/avab/avab/repository/RecreationCustomRepository.java
src/main/java/com/avab/avab/repository/RecreationCustomRepositoryImpl.java
src/main/java/com/avab/avab/repository/RecreationRepository.java
src/main/java/com/avab/avab/repository/RecreationReviewRepository.java
src/main/java/com/avab/avab/service/RecreationService.java
src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java
src/main/java/com/avab/avab/service/impl/RecreationServiceImpl.java
src/main/java/com/avab/avab/service/impl/ReportServiceImpl.java
src/main/java/com/avab/avab/service/impl/UserServiceImpl.java

Close #184 
- 인기 레크레이션, 최신순 레크레이션 API 통합
- 레크레이션 검색시 정렬 문제 해결

✨ [Feat]: 레크레이션 API 통합

---

src/main/java/com/avab/avab/controller/AuthController.java
src/main/java/com/avab/avab/security/handler/resolver/ExtractTokenArgumentResolver.java

Close #188 
- refresh token Bearer 토큰 추가
265bc8fd4d249f061611faebae8022c397534963
- refreshToken 발급 시 Bearer 처리해주기
b144cb5214ad01266c339c2e9d65525cf66fcd3d
- refreshToken swagger 숨기기

♻️ [Refactor]: refresh token Bearer 토큰 추가

---

src/main/java/com/avab/avab/controller/UserController.java
src/main/java/com/avab/avab/domain/User.java
src/main/java/com/avab/avab/service/impl/UserServiceImpl.java

Close #195 
- 회원 탈퇴 복구 기능 수정
- 회원 탈퇴 복구 swagger 수정
c49dfd0a8d78c664aa3987ffb9ccd4595b6d8253
- 회원 탈퇴 복구 기능 수정
c5762e496e0af32400366722acf72c1ff9916c4d

🐛 [Fix]: 회원 탈퇴 복구 기능 수정

---

src/main/java/com/avab/avab/repository/FlowCustomRepositoryImpl.java
src/main/java/com/avab/avab/repository/RecreationCustomRepositoryImpl.java

HOTFIX
- 스크랩한 플로우의 페이지네이션이 올바르게 되지 않는 문제 해결

:ambulance: [HOTFIX!]: 스크랩한 플로우 페이지네이션 올바르게 되지 않는 문제 해결

---

src/main/java/com/avab/avab/converter/RecreationConverter.java
src/main/java/com/avab/avab/dto/response/RecreationResponseDTO.java

:ambulance: [HOTFIX!]: 오탈자 수정

---

src/main/java/com/avab/avab/service/impl/RecreationServiceImpl.java

Close #202
- 댓글 리뷰 별점으로 조회되던 인기순 정렬 기준을 즐겨찾기 수 기반으로 변경했습니다.

:sparkles: [Feat] 인기순 정렬 기준을 즐겨찾기 수 기반으로 변경

---

src/main/java/com/avab/avab/domain/Recreation.java
src/main/java/com/avab/avab/service/impl/RecreationServiceImpl.java

Close #203 
- 레크레이션 즐겨찾기 시 개수 업데이트

:sparkles: [Feat]: 레크레이션 즐겨찾기시 즐겨찾기 개수 업데이트

---

src/main/java/com/avab/avab/config/RedisConfig.java
src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java

Close #210 
- flow 조회수 증가 로직 추가
- flow 조회수 증가 로직 추가
[✨ [Feat]: 플로우 조회수 증가시키는 로직 추가](https://github.com/TeamAvAb/AvAb-Back/commit/a5c3e9dd90a837cfdc80b5f9f8136a667a12610c)
[🐛 [Fix]: Redis local 시 ssl 취소](https://github.com/TeamAvAb/AvAb-Back/commit/1fdb9290ca079cbe44fb74cffd0a25d0030c64a8)

✨ [Feat]: flow 조회수 증가 로직 추가

---

src/main/resources/application.yml

Close #
- S3 버킷 이름 하드 코딩 대신 환경 변수로 변경

:ambulance: [HOTFIX!]: s3 bucket 이름 환경 변수로 변경
